include: package:pedantic/analysis_options.yaml
#analyzer:
##   exclude:
##     - path/to/excluded/files/**
#
## Lint rules and documentation, see http://dart-lang.github.io/linter/lints
#linter:
#  rules:
#    - cancel_subscriptions
#    - hash_and_equals
#    - iterable_contains_unrelated_type
#    - list_remove_unrelated_type
#    - test_types_in_equals
#    - unrelated_type_equality_checks
#    - valid_regexps
#    - unawaited_futures
#    - curly_braces_in_flow_control_structures # added for package score in https://pub.dev
linter:
  rules:
    prefer_single_quotes: false
    prefer_double_quotes: false
