import 'globals.dart';
import 'utils.dart' as utils;

/// Archive screenshots generated by a run.
class Archive {
  static final _timeStamp = getTimestamp();

  final _stagingTestDir;
  final archiveDirPrefix;

  Archive(String stagingDir, String archiveDir)
      : _stagingTestDir = '$stagingDir/$kTestScreenshotsDir',
        archiveDirPrefix = '$archiveDir/$_timeStamp';

  /// Move (processed) screenshots generated by last test
  String moveTestScreenshots(DeviceType deviceType, String locale) {
    final testDstDir = dstDir(deviceType, locale);
    utils.moveFiles(_stagingTestDir, testDstDir);
    return testDstDir;
  }

  String dstDir(DeviceType deviceType, String locale) =>
      '$archiveDirPrefix/${utils.getStringFromEnum(deviceType)}/$locale';
}

/// Generates timestamp as [DateTime] in milliseconds
DateTime getTimestamp() {
  final timestamp = DateTime.fromMillisecondsSinceEpoch(
      DateTime.now().millisecondsSinceEpoch);
  return timestamp;
}
