#!/usr/bin/env bash

# Originally written by Ralf Kistner <ralf@embarkmobile.com>, but placed in the public domain
# Adapted by Maurice McCabe <mmcc007@gmail.com>, but placed in the public domain

set +e

bootanim=""
failcounter=0
timeout_in_sec=360

until [[ "$bootanim" =~ "error: no emulators found" ]]; do
#until [[ "$bootanim" =~ "error: closed" ]]; do
  bootanim=`adb -s $1 -e shell getprop init.svc.bootanim 2>&1 &`
  #echo $bootanim
  if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline"
    || "$bootanim" =~ "running" || "$bootanim" =~ "stopped" ]]; then
    let "failcounter += 1"
    echo "Waiting for emulator to stop"
    if [[ $failcounter -gt timeout_in_sec ]]; then
      echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
      exit 1
    fi
  fi
  sleep 1
done

echo "Emulator is stopped"